### ISSUE TITLE
Add push! without the iterator arg

### ISSUE THREAD

**Issue by tbreloff** [JuliaML/ValueHistories.jl#1]
For example, I'd like to do:

```
history = DynMultivalueHistory()
for i in 1:10
  push!(history, :a, rand())
  push!(history, :b, rand())
end
```

**Comment by Evizero** [comment]
Well I see what you mean. There is a trade-off though in that an assumption has to be made on how many iterations have passes (where "1" is probably the most useful)

**Comment by Evizero** [comment]
should work on master. I included basic tests. Let me know if you encounter any problems
