### ISSUE TITLE
ValueHistory{V} <: AbstractVector{V}

### ISSUE THREAD

**Issue by EricForgy** [JuliaML/ValueHistories.jl#14]
Would there be any interest in making this change?

```
abstract type ValueHistory{V} <: AbstractVector{V} end
abstract type UnivalueHistory{I,V} <: ValueHistory{V} end
```

Primary reason would be able to index into the values using an iteration value.

Edit: In my case, I am considering to use this package for observations where the iterations are observation timestamps.

**Comment by Evizero** [comment]
In its current design this wouldn't work for multiple reasons

- `QHistory` (implemented as a `Deque`) doesn't provide `getindex`. 
- A `MVHistory` (also subtype of `ValueHistory`) doesn't require each tracked variable to be sampled in the same iterations (see readme example). So there is no clear meaning for a unique index for the whole history.

**Comment by Evizero** [comment]
What is the motivation behind this idea? Is there something concrete where the current situation is an obstacle, or your proposal would help?

**Comment by EricForgy** [comment]
Thanks @Evizero . I decided to go with another solution for now 😊
