### ISSUE TITLE
Migrate Recipes into this package

### ISSUE THREAD

**Issue by Evizero** [JuliaML/ValueHistories.jl#2]
from: https://github.com/JuliaML/MLPlots.jl/blob/master/src/ValueHistories/ValueHistories.jl
cc: @tbreloff 

I will try to do this now. This issue is mainly to keep you updated

**Comment by tbreloff** [comment]
Ok just be warned that we'll have to make some changes to recipes when i
merge/tag the Plots branch I'm working on. Not much, but they'll probably
break.

**Comment by Evizero** [comment]
I see. Well In that case I shall work in the dev branch and later squash commits to not have useless images float around the git history

**Comment by Evizero** [comment]
Look at those images: https://github.com/JuliaML/ValueHistories.jl/commit/9efb8e8571655615e4f295aa58be6bf540bc4e10 . Each image is just around 10kb of size. They do seem decent enough for testing don't they?

**Comment by Evizero** [comment]
Travis is failing currently. I take it the RecipeBase stuff is not tagged in Plots yet, right? Regardless, there is no hurry. Just wanted to get ahead of the curve a bit

**Comment by Evizero** [comment]
Concerning the images, I wish the zooming out was a bit more graceful. Can you think of a bunch of options that would make those reference images "good enough" to be used in the readme?

**Comment by Evizero** [comment]
like decreasing font, legend size, and such

**Comment by tbreloff** [comment]
Yes I agree completely. I'm thinking through the redesign of
layouts/subplots, and this is the sort of thing that I hope I'm able to
solve.

**Comment by Evizero** [comment]
How is progress in Plots concerning:

> Ok just be warned that we'll have to make some changes to recipes when i merge/tag the Plots branch I'm working on. Not much, but they'll probably break.

Stable enough to include the recipes here now?

**Comment by tbreloff** [comment]
Should be stable enough... I'll take a look at them soon.

**Comment by Evizero** [comment]
bump. I suspect RecipesBase has settled to a more or less stable point @tbreloff ?

**Comment by Evizero** [comment]
Let me know if you think I should change something about the recipes. I close this for now

**Comment by Evizero** [comment]
I'll abuse this issue as screenshot storage for readme previews

<img width="238" alt="multivalue" src="https://cloud.githubusercontent.com/assets/10854026/17746217/70d0ad9c-64af-11e6-8453-bf94aad32571.png">

<img width="239" alt="univalue" src="https://cloud.githubusercontent.com/assets/10854026/17746218/70d10760-64af-11e6-94c4-b711a9ac018b.png">
