### ISSUE TITLE
Names and roadmap

### ISSUE THREAD

**Issue by tbreloff** [JuliaML/ValueHistories.jl#7]
Some name bikeshedding.  The names are too complex and long.  I need to look at the code/readme every single time I use it.

VectorUnivalueHistory --> Hist
QueueUnivalueHistory --> QueueHist
DynMultivalueHistory --> MultiHist

and I don't see a strong reason for the type tree.  Can we get rid of it, or at least make them all `<: AbstractHist`?

General thoughts:
- Plotting a MultiHist should be like DataFrames, except that it fills in `x` values for corresponding `y` values
- It should be possible to use keys other than Symbol
- No "increasing iterations" requirement... any data can go in

Anything else while I'm working on it?

**Comment by Evizero** [comment]
I like the names 👍

**Comment by Evizero** [comment]
> and I don't see a strong reason for the type tree. Can we get rid of it, or at least make them all

why?? they make the code a little less cluttered and there is literally no downside to having them. Also there is the benefit that users can generalize code to having "some univalue history" or something of that sort

**Comment by joshday** [comment]
I would vote to keep -ory, and maybe DynMultivalueHistory --> MVHistory (somewhat consistent with Distributions)

**Comment by Evizero** [comment]
I am all for nicer plots if you are interested in implementing them 👍 . The main reasons the recipes are currently simple is because 1.) I don't yet have a clear understanding of the possibilities that recipes provides, and 2.) I haven't had a real need for them and just wanted to provide some basic support

**Comment by Evizero** [comment]
> I would vote to keep -ory, and maybe DynMultivalueHistory --> MVHistory (somewhat consistent with Distributions)

I like that

**Comment by Evizero** [comment]
what about `QHistory` ?

**Comment by tbreloff** [comment]
History, QHistory, and Histories?

**Comment by Evizero** [comment]
I prefer `MVHistory` over `Histories`

**Comment by tbreloff** [comment]
Hist/QHist/Hists?  Do you want the `-ory` because of confusion with histogram?

**Comment by joshday** [comment]
Partially.  Three letters for clarity seems a good trade.  I think I also prefer MVHistory.

**Comment by tbreloff** [comment]
Ok votes are in... I'll make the changes

**Comment by Evizero** [comment]
thanks!
